directory: ~/Dropbox (Personal)/Music/Library
library: ~/Dropbox (Personal)/Music/Library/.library.blb

paths:
  singleton: _Non-Album/$artist/$title

plugins:
  - acousticbrainz
  - embedart
  - fetchart
  - lastgenre
  - lyrics
  - missing
  - mpdupdate

import:
  incremental: yes
  quiet_fallback: skip

mpd:
  host: localhost
  port: 6600
