#!/usr/bin/env bash

function install_homebrew_dependencies() {
  brew tap 'homebrew/bundle'
  brew tap 'caskroom/cask'
  brew tap 'caskroom/fonts'
  brew tap 'caskroom/versions'
  brew tap 'homebrew/core'
  brew tap 'homebrew/services'
  brew tap 'homebrew/versions'
  if [ -f "$HOME/.Brewfile.dot-media" ]; then
    echo "Installing Homebrew Dependencies"
    brew bundle --file="$HOME/.Brewfile.dot-media"
  else
    echo "Installing Homebrew Dependencies from $PKG_PATH/Brewfile.dot-media"
    brew bundle --file="$PKG_PATH/Brewfile.dot-media"
  fi
}

function install_python_packages() {
  echo "Installing python packages"
  pip install -U beets
  pip install -U pylast
  pip install -U requests
}

install_homebrew_dependencies
install_python_packages
