#!/usr/bin/env bash

function install_homebrew_dependencies() {
  brew tap 'homebrew/bundle'
  brew tap 'caskroom/cask'
  brew tap 'caskroom/fonts'
  brew tap 'caskroom/versions'
  brew tap 'homebrew/core'
  brew tap 'homebrew/services'
  brew tap 'homebrew/versions'
  echo "Installing Homebrew Dependencies"
  brew bundle --file="$HOME/.Brewfile.dotfiles-media"
}

function install_python_packages() {
  echo "Installing python packages"
  pip install -U beets
  pip install -U pylast
  pip install -U requests
}

install_homebrew_dependencies
install_python_packages
